# places_types.py
# Lookup table for Google Places (New) API types with human-friendly synonyms

PLACE_TYPE_MAP = {
    # Food & Drink
    "restaurant": "restaurant",
    "restaurants": "restaurant",
    "food": "restaurant",
    "cafe": "cafe",
    "coffee": "cafe",
    "coffee shop": "cafe",
    "bakery": "bakery",
    "bar": "bar",
    "pub": "bar",
    "nightclub": "night_club",
    "club": "night_club",

    # Shopping
    "grocery": "supermarket",
    "grocery store": "supermarket",
    "supermarket": "supermarket",
    "market": "supermarket",
    "convenience store": "convenience_store",
    "corner store": "convenience_store",
    "hardware": "hardware_store",
    "hardware store": "hardware_store",
    "pharmacy": "pharmacy",
    "drugstore": "drugstore",
    "mall": "shopping_mall",
    "shopping mall": "shopping_mall",
    "clothes": "clothing_store",
    "clothing": "clothing_store",
    "clothing store": "clothing_store",
    "bookstore": "book_store",
    "book store": "book_store",
    "jewelry": "jewelry_store",
    "jewelry store": "jewelry_store",
    "electronics": "electronics_store",
    "electronics store": "electronics_store",
    "shoe store": "shoe_store",
    "liquor store": "liquor_store",
    "furniture store": "furniture_store",
    "pet store": "pet_store",

    # Essentials & Services
    "atm": "atm",
    "bank": "bank",
    "post office": "post_office",
    "mail": "post_office",
    "library": "library",
    "hospital": "hospital",
    "doctor": "doctor",
    "dentist": "dentist",
    "pharmacy": "pharmacy",
    "drug store": "drugstore",
    "lawyer": "lawyer",
    "plumber": "plumber",
    "electrician": "electrician",
    "insurance": "insurance_agency",
    "insurance agency": "insurance_agency",
    "police": "police",
    "fire station": "fire_station",
    "funeral home": "funeral_home",
    "cemetery": "cemetery",
    "church": "church",
    "mosque": "mosque",
    "synagogue": "synagogue",
    "hindu temple": "hindu_temple",

    # Transport
    "train": "train_station",
    "train station": "train_station",
    "bus": "bus_station",
    "bus station": "bus_station",
    "subway": "subway_station",
    "metro": "subway_station",
    "light rail": "light_rail_station",
    "airport": "airport",
    "taxi": "taxi_stand",
    "parking": "parking",
    "transit": "transit_station",

    # Lodging & Travel
    "hotel": "lodging",
    "lodging": "lodging",
    "motel": "lodging",
    "rv park": "rv_park",
    "campground": "campground",
    "travel agency": "travel_agency",

    # Leisure & Entertainment
    "park": "park",
    "amusement park": "amusement_park",
    "theme park": "amusement_park",
    "museum": "museum",
    "zoo": "zoo",
    "aquarium": "aquarium",
    "stadium": "stadium",
    "casino": "casino",
    "movie theater": "movie_theater",
    "cinema": "movie_theater",
    "movies": "movie_theater",
    "bowling": "bowling_alley",
    "bowling alley": "bowling_alley",
    "art gallery": "art_gallery",
    "tourist attraction": "tourist_attraction",

    # Schools & Education
    "school": "school",
    "primary school": "primary_school",
    "elementary school": "primary_school",
    "secondary school": "secondary_school",
    "high school": "secondary_school",
    "university": "university",
    "college": "university",

    # Home & Services
    "storage": "storage",
    "moving company": "moving_company",
    "real estate": "real_estate_agency",
    "real estate agency": "real_estate_agency",
    "painter": "painter",
    "roofing": "roofing_contractor",
    "roofing contractor": "roofing_contractor",
    "locksmith": "locksmith",
    "laundry": "laundry",
    "gym": "gym",
    "spa": "spa",
    "beauty salon": "beauty_salon",
    "hair salon": "hair_care",
    "barber": "hair_care",

    # Government & Civic
    "city hall": "city_hall",
    "courthouse": "courthouse",
    "embassy": "embassy",
    "local government": "local_government_office",
}
